# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.4

# Default target executed when no arguments are given to make.
default_target: all

.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:


#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:


# Remove some rules from gmake that .SUFFIXES does not remove.
SUFFIXES =

.SUFFIXES: .hpux_make_needs_suffix_list


# Suppress display of executed commands.
$(VERBOSE).SILENT:


# A target that is always out of date.
cmake_force:

.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/local/Cellar/cmake/3.4.2/bin/cmake

# The command to remove a file.
RM = /usr/local/Cellar/cmake/3.4.2/bin/cmake -E remove -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = "/Users/nursultan/Desktop/NU/Fall 2016/PhotoMosaic"

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = "/Users/nursultan/Desktop/NU/Fall 2016/PhotoMosaic"

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake cache editor..."
	/usr/local/Cellar/cmake/3.4.2/bin/ccmake -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache

.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/usr/local/Cellar/cmake/3.4.2/bin/cmake -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache

.PHONY : rebuild_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start "/Users/nursultan/Desktop/NU/Fall 2016/PhotoMosaic/CMakeFiles" "/Users/nursultan/Desktop/NU/Fall 2016/PhotoMosaic/CMakeFiles/progress.marks"
	$(MAKE) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start "/Users/nursultan/Desktop/NU/Fall 2016/PhotoMosaic/CMakeFiles" 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean

.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named createDataset

# Build rule for target.
createDataset: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 createDataset
.PHONY : createDataset

# fast build rule for target.
createDataset/fast:
	$(MAKE) -f CMakeFiles/createDataset.dir/build.make CMakeFiles/createDataset.dir/build
.PHONY : createDataset/fast

#=============================================================================
# Target rules for targets named main

# Build rule for target.
main: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 main
.PHONY : main

# fast build rule for target.
main/fast:
	$(MAKE) -f CMakeFiles/main.dir/build.make CMakeFiles/main.dir/build
.PHONY : main/fast

#=============================================================================
# Target rules for targets named photoMosaicAverageRGB

# Build rule for target.
photoMosaicAverageRGB: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 photoMosaicAverageRGB
.PHONY : photoMosaicAverageRGB

# fast build rule for target.
photoMosaicAverageRGB/fast:
	$(MAKE) -f CMakeFiles/photoMosaicAverageRGB.dir/build.make CMakeFiles/photoMosaicAverageRGB.dir/build
.PHONY : photoMosaicAverageRGB/fast

#=============================================================================
# Target rules for targets named photoMosaicAverageRGBFaceDetector

# Build rule for target.
photoMosaicAverageRGBFaceDetector: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 photoMosaicAverageRGBFaceDetector
.PHONY : photoMosaicAverageRGBFaceDetector

# fast build rule for target.
photoMosaicAverageRGBFaceDetector/fast:
	$(MAKE) -f CMakeFiles/photoMosaicAverageRGBFaceDetector.dir/build.make CMakeFiles/photoMosaicAverageRGBFaceDetector.dir/build
.PHONY : photoMosaicAverageRGBFaceDetector/fast

src/createDataset.o: src/createDataset.cpp.o

.PHONY : src/createDataset.o

# target to build an object file
src/createDataset.cpp.o:
	$(MAKE) -f CMakeFiles/createDataset.dir/build.make CMakeFiles/createDataset.dir/src/createDataset.cpp.o
.PHONY : src/createDataset.cpp.o

src/createDataset.i: src/createDataset.cpp.i

.PHONY : src/createDataset.i

# target to preprocess a source file
src/createDataset.cpp.i:
	$(MAKE) -f CMakeFiles/createDataset.dir/build.make CMakeFiles/createDataset.dir/src/createDataset.cpp.i
.PHONY : src/createDataset.cpp.i

src/createDataset.s: src/createDataset.cpp.s

.PHONY : src/createDataset.s

# target to generate assembly for a file
src/createDataset.cpp.s:
	$(MAKE) -f CMakeFiles/createDataset.dir/build.make CMakeFiles/createDataset.dir/src/createDataset.cpp.s
.PHONY : src/createDataset.cpp.s

src/main.o: src/main.cpp.o

.PHONY : src/main.o

# target to build an object file
src/main.cpp.o:
	$(MAKE) -f CMakeFiles/main.dir/build.make CMakeFiles/main.dir/src/main.cpp.o
.PHONY : src/main.cpp.o

src/main.i: src/main.cpp.i

.PHONY : src/main.i

# target to preprocess a source file
src/main.cpp.i:
	$(MAKE) -f CMakeFiles/main.dir/build.make CMakeFiles/main.dir/src/main.cpp.i
.PHONY : src/main.cpp.i

src/main.s: src/main.cpp.s

.PHONY : src/main.s

# target to generate assembly for a file
src/main.cpp.s:
	$(MAKE) -f CMakeFiles/main.dir/build.make CMakeFiles/main.dir/src/main.cpp.s
.PHONY : src/main.cpp.s

src/photoMosaicAverageRGB.o: src/photoMosaicAverageRGB.cpp.o

.PHONY : src/photoMosaicAverageRGB.o

# target to build an object file
src/photoMosaicAverageRGB.cpp.o:
	$(MAKE) -f CMakeFiles/photoMosaicAverageRGB.dir/build.make CMakeFiles/photoMosaicAverageRGB.dir/src/photoMosaicAverageRGB.cpp.o
.PHONY : src/photoMosaicAverageRGB.cpp.o

src/photoMosaicAverageRGB.i: src/photoMosaicAverageRGB.cpp.i

.PHONY : src/photoMosaicAverageRGB.i

# target to preprocess a source file
src/photoMosaicAverageRGB.cpp.i:
	$(MAKE) -f CMakeFiles/photoMosaicAverageRGB.dir/build.make CMakeFiles/photoMosaicAverageRGB.dir/src/photoMosaicAverageRGB.cpp.i
.PHONY : src/photoMosaicAverageRGB.cpp.i

src/photoMosaicAverageRGB.s: src/photoMosaicAverageRGB.cpp.s

.PHONY : src/photoMosaicAverageRGB.s

# target to generate assembly for a file
src/photoMosaicAverageRGB.cpp.s:
	$(MAKE) -f CMakeFiles/photoMosaicAverageRGB.dir/build.make CMakeFiles/photoMosaicAverageRGB.dir/src/photoMosaicAverageRGB.cpp.s
.PHONY : src/photoMosaicAverageRGB.cpp.s

src/photoMosaicAverageRGBFaceDetector.o: src/photoMosaicAverageRGBFaceDetector.cpp.o

.PHONY : src/photoMosaicAverageRGBFaceDetector.o

# target to build an object file
src/photoMosaicAverageRGBFaceDetector.cpp.o:
	$(MAKE) -f CMakeFiles/photoMosaicAverageRGBFaceDetector.dir/build.make CMakeFiles/photoMosaicAverageRGBFaceDetector.dir/src/photoMosaicAverageRGBFaceDetector.cpp.o
.PHONY : src/photoMosaicAverageRGBFaceDetector.cpp.o

src/photoMosaicAverageRGBFaceDetector.i: src/photoMosaicAverageRGBFaceDetector.cpp.i

.PHONY : src/photoMosaicAverageRGBFaceDetector.i

# target to preprocess a source file
src/photoMosaicAverageRGBFaceDetector.cpp.i:
	$(MAKE) -f CMakeFiles/photoMosaicAverageRGBFaceDetector.dir/build.make CMakeFiles/photoMosaicAverageRGBFaceDetector.dir/src/photoMosaicAverageRGBFaceDetector.cpp.i
.PHONY : src/photoMosaicAverageRGBFaceDetector.cpp.i

src/photoMosaicAverageRGBFaceDetector.s: src/photoMosaicAverageRGBFaceDetector.cpp.s

.PHONY : src/photoMosaicAverageRGBFaceDetector.s

# target to generate assembly for a file
src/photoMosaicAverageRGBFaceDetector.cpp.s:
	$(MAKE) -f CMakeFiles/photoMosaicAverageRGBFaceDetector.dir/build.make CMakeFiles/photoMosaicAverageRGBFaceDetector.dir/src/photoMosaicAverageRGBFaceDetector.cpp.s
.PHONY : src/photoMosaicAverageRGBFaceDetector.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... edit_cache"
	@echo "... rebuild_cache"
	@echo "... photoMosaicAverageRGBFaceDetector"
	@echo "... photoMosaicAverageRGB"
	@echo "... createDataset"
	@echo "... main"
	@echo "... src/createDataset.o"
	@echo "... src/createDataset.i"
	@echo "... src/createDataset.s"
	@echo "... src/main.o"
	@echo "... src/main.i"
	@echo "... src/main.s"
	@echo "... src/photoMosaicAverageRGB.o"
	@echo "... src/photoMosaicAverageRGB.i"
	@echo "... src/photoMosaicAverageRGB.s"
	@echo "... src/photoMosaicAverageRGBFaceDetector.o"
	@echo "... src/photoMosaicAverageRGBFaceDetector.i"
	@echo "... src/photoMosaicAverageRGBFaceDetector.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

